In [1]:
import numpy as np

In [2]:
#1
a = np.arange(1, 11, 1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#2
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
#3
a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 3  5  6  9  6]
 [ 8 10 10  5  4]
 [ 6  9  4  9  6]
 [ 5  3  5 10  2]
 [ 7  7  2  8  8]]


In [5]:
#4
a = np.random.random((4, 4))
print(a)

[[0.86590823 0.17823542 0.6029116  0.30705297]
 [0.25216465 0.3093716  0.68818594 0.95847531]
 [0.21549963 0.61261523 0.77536502 0.29948817]
 [0.25839366 0.70670572 0.47279857 0.55852115]]


In [6]:
#5
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(a)
print(b)
print(f"Dodawanie: {a + b}")
print(f"Odejmowanie: {a - b}")
print(f"Mnożenie: {a * b}")

[2 5 1 9 2]
[7 3 8 1 2]
Dodawanie: [ 9  8  9 10  4]
Odejmowanie: [-5  2 -7  8  0]
Mnożenie: [14 15  8  9  4]


In [7]:
#6
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a, b))

[0.44059905 0.35616924 0.40699408 0.64578396 0.38284778 0.73049752
 0.11137733]
[0.16151111 0.35785167 0.60870065 0.41134089 0.8146657  0.59014836
 0.15756434]
1.4725362729599054


In [8]:
#7
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[5 9]
 [1 4]]
[[4 4 8]
 [4 8 3]]
[[56 92 67]
 [20 36 20]]


In [9]:
#8
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[ 9  6  3]
 [10 10  4]
 [ 9  5  4]]
[[ 0.55555556 -0.25       -0.16666667]
 [-0.11111111  0.25       -0.16666667]
 [-1.11111111  0.25        0.83333333]]


In [10]:
#9
a = np.random.random((4, 4))
b = a.T
print(b)

[[0.46935392 0.0711809  0.32839442 0.89938785]
 [0.01308026 0.29048826 0.4662629  0.30710058]
 [0.1858332  0.42286659 0.32872312 0.7649868 ]
 [0.54896007 0.84714043 0.27343871 0.47769898]]


In [11]:
#10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 5 10  5  8]
 [ 9 10  8  5]
 [ 7  2  3 10]]
[3 4 3 5]
[110 116  88]


In [12]:
#11
a = np.random.random((2, 3))
b = np.random.random(3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[0.00209596 0.71670113 0.30698241]
 [0.62540296 0.22473656 0.74895263]]
[0.18896526 0.93668451 0.47158256]
[0.81648645 0.68187969]


In [13]:
#12
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a * b
print(a)
print(b)
print(c)

[[10 10]
 [ 4  3]]
[[10  7]
 [ 9  9]]
[[100  70]
 [ 36  27]]


In [14]:
#13
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 6  1]
 [10  8]]
[[1 9]
 [6 7]]
[[ 12  61]
 [ 58 146]]


In [15]:
#14
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a.sum())

[[ 94  15  20  27  12]
 [ 82  32  56  61  30]
 [ 71 100  24  60  53]
 [ 49  35  10 100  58]
 [ 67   5  67  92  82]]
1302


In [16]:
#15
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a)
print(b)
print(a - b)

[[ 6  7  2  3]
 [ 9 10  2  4]
 [ 3  5  7  3]
 [10 10  9  3]]
[[ 3  8  5  1]
 [ 2  2  3 10]
 [ 7 10  4  6]
 [ 6  8  5  6]]
[[ 3 -1 -3  2]
 [ 7  8 -1 -6]
 [-4 -5  3 -3]
 [ 4  2  4 -3]]


In [17]:
#16
a = np.random.random((3, 3))
a1 = a[:, 0]
a2 = a[:, 1]
a3 = a[:, 2]
b = np.array([[a1.sum()], [a2.sum()], [a3.sum()]])
print(a)
print(b)

[[0.92574459 0.46050597 0.65412909]
 [0.52280137 0.7637324  0.27935153]
 [0.79989973 0.52676127 0.19665662]]
[[2.24844569]
 [1.75099963]
 [1.13013725]]


In [18]:
#17
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.square(a)
print(b)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [19]:
#18
a = np.random.randint(1, 51, size=4)
b = np.sqrt(a)
print(a)
print(b)

[23 23  8 14]
[4.79583152 4.79583152 2.82842712 3.74165739]
